/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { providers, Signer, ethers } from "ethers";
import React, { useEffect, useState } from "react";
import Web3Modal, { IProviderOptions } from "web3modal";
import { Logs } from "./typechain/Logs";
import { Logs__factory } from "./typechain/factories/Logs__factory";
import { SimpleTokenTimelock } from "./typechain/SimpleTokenTimelock";
import { SimpleTokenTimelock__factory } from "./typechain/factories/SimpleTokenTimelock__factory";
import MonkeDeployment from "./deployments/matic/Monke.json";
import { Monke } from "./typechain/Monke";
import { Monke__factory } from "./typechain/factories/Monke__factory";
import NanerDeployment from "./deployments/matic/Naner.json";
import { Naner } from "./typechain/Naner";
import { Naner__factory } from "./typechain/factories/Naner__factory";
import MonkeBonfireDeployment from "./deployments/matic/MonkeBonfire.json";
import { MonkeBonfire } from "./typechain/MonkeBonfire";
import { MonkeBonfire__factory } from "./typechain/factories/MonkeBonfire__factory";
import { TokenBonfire } from "./typechain/TokenBonfire";
import { TokenBonfire__factory } from "./typechain/factories/TokenBonfire__factory";
import { ERC20 } from "./typechain/ERC20";
import { ERC20__factory } from "./typechain/factories/ERC20__factory";
import { TokenTimelock } from "./typechain/TokenTimelock";
import { TokenTimelock__factory } from "./typechain/factories/TokenTimelock__factory";
import { ERC20PresetFixedSupply } from "./typechain/ERC20PresetFixedSupply";
import { ERC20PresetFixedSupply__factory } from "./typechain/factories/ERC20PresetFixedSupply__factory";

const emptyContract = {
    instance: undefined,
    factory: undefined
};
const defaultProvider: providers.Provider | undefined = undefined;
export const ProviderContext = React.createContext<[providers.Provider | undefined, React.Dispatch<React.SetStateAction<providers.Provider | undefined>>]>([defaultProvider, () => { }]);
const defaultCurrentAddress: string = "";
export const CurrentAddressContext = React.createContext<[string, React.Dispatch<React.SetStateAction<string>>]>([defaultCurrentAddress, () => { }]);
const defaultSigner: Signer | undefined = undefined;
export const SignerContext = React.createContext<[Signer | undefined, React.Dispatch<React.SetStateAction<Signer | undefined>>]>([defaultSigner, () => { }]);
const defaultSymfoniContext: SymfoniContextInterface = {
    currentHardhatProvider: "",
    init: () => { throw Error("Symfoni context not initialized") },
    loading: false,
    messages: [],
    providers: []
};
export const SymfoniContext = React.createContext<SymfoniContextInterface>(defaultSymfoniContext);
export const LogsContext = React.createContext<SymfoniLogs>(emptyContract);
export const SimpleTokenTimelockContext = React.createContext<SymfoniSimpleTokenTimelock>(emptyContract);
export const MonkeContext = React.createContext<SymfoniMonke>(emptyContract);
export const NanerContext = React.createContext<SymfoniNaner>(emptyContract);
export const MonkeBonfireContext = React.createContext<SymfoniMonkeBonfire>(emptyContract);
export const TokenBonfireContext = React.createContext<SymfoniTokenBonfire>(emptyContract);
export const ERC20Context = React.createContext<SymfoniERC20>(emptyContract);
export const TokenTimelockContext = React.createContext<SymfoniTokenTimelock>(emptyContract);
export const ERC20PresetFixedSupplyContext = React.createContext<SymfoniERC20PresetFixedSupply>(emptyContract);

export interface SymfoniContextInterface {
    init: (provider?: string) => void;
    loading: boolean;
    messages: string[];
    currentHardhatProvider: string;
    providers: string[];
}

export interface SymfoniProps {
    autoInit?: boolean;
    showLoading?: boolean;
    loadingComponent?: React.ReactNode;
}

export interface SymfoniLogs {
    instance?: Logs;
    factory?: Logs__factory;
}

export interface SymfoniSimpleTokenTimelock {
    instance?: SimpleTokenTimelock;
    factory?: SimpleTokenTimelock__factory;
}

export interface SymfoniMonke {
    instance?: Monke;
    factory?: Monke__factory;
}

export interface SymfoniNaner {
    instance?: Naner;
    factory?: Naner__factory;
}

export interface SymfoniMonkeBonfire {
    instance?: MonkeBonfire;
    factory?: MonkeBonfire__factory;
}

export interface SymfoniTokenBonfire {
    instance?: TokenBonfire;
    factory?: TokenBonfire__factory;
}

export interface SymfoniERC20 {
    instance?: ERC20;
    factory?: ERC20__factory;
}

export interface SymfoniTokenTimelock {
    instance?: TokenTimelock;
    factory?: TokenTimelock__factory;
}

export interface SymfoniERC20PresetFixedSupply {
    instance?: ERC20PresetFixedSupply;
    factory?: ERC20PresetFixedSupply__factory;
}

export const Symfoni: React.FC<SymfoniProps> = ({
    showLoading = true,
    autoInit = true,
    ...props
}) => {
    const [initializeCounter, setInitializeCounter] = useState(0);
    const [currentHardhatProvider, setCurrentHardhatProvider] = useState("");
    const [loading, setLoading] = useState(false);
    const [messages, setMessages] = useState<string[]>([]);
    const [signer, setSigner] = useState<Signer | undefined>(defaultSigner);
    const [provider, setProvider] = useState<providers.Provider | undefined>(defaultProvider);
    const [currentAddress, setCurrentAddress] = useState<string>(defaultCurrentAddress);
    const [fallbackProvider] = useState<string | undefined>(undefined);
    const [providerPriority, setProviderPriority] = useState<string[]>(["web3modal", "hardhat"]);
    const [Logs, setLogs] = useState<SymfoniLogs>(emptyContract);
    const [SimpleTokenTimelock, setSimpleTokenTimelock] = useState<SymfoniSimpleTokenTimelock>(emptyContract);
    const [Monke, setMonke] = useState<SymfoniMonke>(emptyContract);
    const [Naner, setNaner] = useState<SymfoniNaner>(emptyContract);
    const [MonkeBonfire, setMonkeBonfire] = useState<SymfoniMonkeBonfire>(emptyContract);
    const [TokenBonfire, setTokenBonfire] = useState<SymfoniTokenBonfire>(emptyContract);
    const [ERC20, setERC20] = useState<SymfoniERC20>(emptyContract);
    const [TokenTimelock, setTokenTimelock] = useState<SymfoniTokenTimelock>(emptyContract);
    const [ERC20PresetFixedSupply, setERC20PresetFixedSupply] = useState<SymfoniERC20PresetFixedSupply>(emptyContract);
    useEffect(() => {
        if (messages.length > 0)
            console.debug(messages.pop())
    }, [messages])

    const getProvider = async (): Promise<{ provider: providers.Provider, hardhatProviderName: string } | undefined> => {
        let hardhatProviderName = "Not set";
        let _providerPriority = [...providerPriority];
        // Fallback provider
        if (fallbackProvider && autoInit && initializeCounter === 0) {
            if (localStorage.getItem("WEB3_CONNECT_CACHED_PROVIDER") === null) {
                _providerPriority = _providerPriority.sort((a, b) => {
                    return a === fallbackProvider ? -1 : b === fallbackProvider ? 1 : 0;
                })
            }
        }
        const provider = await _providerPriority.reduce(async (maybeProvider: Promise<providers.Provider | undefined>, providerIdentification) => {
            let foundProvider = await maybeProvider
            if (foundProvider) {
                return Promise.resolve(foundProvider)
            }
            else {
                switch (providerIdentification.toLowerCase()) {
                    case "web3modal":
                        try {
                            const provider = await getWeb3ModalProvider()
                            const web3provider = new ethers.providers.Web3Provider(provider);
                            hardhatProviderName = "web3modal";
                            return Promise.resolve(web3provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        }
                    case "hardhat":
                        try {
                            const provider = new ethers.providers.JsonRpcProvider({
                                url: "http://127.0.0.1:8545",
                            });
                            hardhatProviderName = "hardhat";
                            return Promise.resolve(provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        } default:
                        return Promise.resolve(undefined)
                }
            }
        }, Promise.resolve(undefined)) // end reduce
        return provider ? { provider, hardhatProviderName } : undefined
    };
    const getSigner = async (_provider: providers.Provider, hardhatProviderName: string): Promise<Signer | undefined> => {
        switch (hardhatProviderName) {
            case "web3modal":
                const web3provider = _provider as ethers.providers.Web3Provider
                return await web3provider.getSigner()
            case "hardhat":
                return ethers.Wallet.fromMnemonic("test test test test test test test test test test test junk").connect(_provider)
            default:
                return undefined
        }
    };
    const getWeb3ModalProvider = async (): Promise<any> => {
        const providerOptions: IProviderOptions = {

        };
        const web3Modal = new Web3Modal({
            // network: "mainnet",
            cacheProvider: false,
            providerOptions, // required
        });
        return await web3Modal.connect();
    };

    useEffect(() => {
        let subscribed = true
        const doAsync = async () => {
            const finish = (text: string) => {
                setLoading(false)
                setMessages(old => [...old, text])
            }
            const finishWithContracts = (text: string) => {
                setLogs(getLogs(_provider, _signer))
                setSimpleTokenTimelock(getSimpleTokenTimelock(_provider, _signer))
                setMonke(getMonke(_provider, _signer))
                setNaner(getNaner(_provider, _signer))
                setMonkeBonfire(getMonkeBonfire(_provider, _signer))
                setTokenBonfire(getTokenBonfire(_provider, _signer))
                setERC20(getERC20(_provider, _signer))
                setTokenTimelock(getTokenTimelock(_provider, _signer))
                setERC20PresetFixedSupply(getERC20PresetFixedSupply(_provider, _signer))
                finish(text)
            }
            if (!autoInit && initializeCounter === 0) return finish("Auto init turned off.")
            setLoading(true)
            setMessages(old => [...old, "Initiating Symfoni React"])
            const providerObject = await getProvider() // getProvider can actually return undefined, see issue https://github.com/microsoft/TypeScript/issues/11094

            if (!subscribed || !providerObject) return finish("No provider or signer.")
            const _provider = providerObject.provider
            setProvider(_provider)
            setMessages(old => [...old, "Useing " + providerObject.hardhatProviderName])
            setCurrentHardhatProvider(providerObject.hardhatProviderName)
            const _signer = await getSigner(_provider, providerObject.hardhatProviderName);

            if (!subscribed || !_signer) return finishWithContracts("Provider, without signer.")
            setSigner(_signer)
            setMessages(old => [...old, "Useing signer"])
            const address = await _signer.getAddress()

            if (!subscribed || !address) return finishWithContracts("Provider and signer, without address.")
            setCurrentAddress(address)

            return finishWithContracts("Completed Symfoni context initialization.")
        };
        doAsync();
        return () => { subscribed = false }
    }, [initializeCounter])

    const getLogs = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? Logs__factory.connect(ethers.constants.AddressZero, _signer) : Logs__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniLogs = {
            instance: instance,
            factory: _signer ? new Logs__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getSimpleTokenTimelock = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? SimpleTokenTimelock__factory.connect(ethers.constants.AddressZero, _signer) : SimpleTokenTimelock__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniSimpleTokenTimelock = {
            instance: instance,
            factory: _signer ? new SimpleTokenTimelock__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getMonke = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = MonkeDeployment.receipt.contractAddress
        const instance = _signer ? Monke__factory.connect(contractAddress, _signer) : Monke__factory.connect(contractAddress, _provider)
        const contract: SymfoniMonke = {
            instance: instance,
            factory: _signer ? new Monke__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getNaner = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = NanerDeployment.receipt.contractAddress
        const instance = _signer ? Naner__factory.connect(contractAddress, _signer) : Naner__factory.connect(contractAddress, _provider)
        const contract: SymfoniNaner = {
            instance: instance,
            factory: _signer ? new Naner__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getMonkeBonfire = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = MonkeBonfireDeployment.receipt.contractAddress
        const instance = _signer ? MonkeBonfire__factory.connect(contractAddress, _signer) : MonkeBonfire__factory.connect(contractAddress, _provider)
        const contract: SymfoniMonkeBonfire = {
            instance: instance,
            factory: _signer ? new MonkeBonfire__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getTokenBonfire = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? TokenBonfire__factory.connect(ethers.constants.AddressZero, _signer) : TokenBonfire__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniTokenBonfire = {
            instance: instance,
            factory: _signer ? new TokenBonfire__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC20 = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC20__factory.connect(ethers.constants.AddressZero, _signer) : ERC20__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC20 = {
            instance: instance,
            factory: _signer ? new ERC20__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getTokenTimelock = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? TokenTimelock__factory.connect(ethers.constants.AddressZero, _signer) : TokenTimelock__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniTokenTimelock = {
            instance: instance,
            factory: _signer ? new TokenTimelock__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC20PresetFixedSupply = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC20PresetFixedSupply__factory.connect(ethers.constants.AddressZero, _signer) : ERC20PresetFixedSupply__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC20PresetFixedSupply = {
            instance: instance,
            factory: _signer ? new ERC20PresetFixedSupply__factory(_signer) : undefined,
        }
        return contract
    }
        ;

    const handleInitProvider = (provider?: string) => {
        if (provider) {
            setProviderPriority(old => old.sort((a, b) => {
                return a === provider ? -1 : b === provider ? 1 : 0;
            }))
        }
        setInitializeCounter(initializeCounter + 1)
    }
    return (
        <SymfoniContext.Provider value={{ init: (provider) => handleInitProvider(provider), providers: providerPriority, currentHardhatProvider, loading, messages }}>
            <ProviderContext.Provider value={[provider, setProvider]}>
                <SignerContext.Provider value={[signer, setSigner]}>
                    <CurrentAddressContext.Provider value={[currentAddress, setCurrentAddress]}>
                        <LogsContext.Provider value={Logs}>
                            <SimpleTokenTimelockContext.Provider value={SimpleTokenTimelock}>
                                <MonkeContext.Provider value={Monke}>
                                    <NanerContext.Provider value={Naner}>
                                        <MonkeBonfireContext.Provider value={MonkeBonfire}>
                                            <TokenBonfireContext.Provider value={TokenBonfire}>
                                                <ERC20Context.Provider value={ERC20}>
                                                    <TokenTimelockContext.Provider value={TokenTimelock}>
                                                        <ERC20PresetFixedSupplyContext.Provider value={ERC20PresetFixedSupply}>
                                                            {showLoading && loading ?
                                                                props.loadingComponent
                                                                    ? props.loadingComponent
                                                                    : <div>
                                                                        {messages.map((msg, i) => (
                                                                            <p key={i}>{msg}</p>
                                                                        ))}
                                                                    </div>
                                                                : props.children
                                                            }
                                                        </ERC20PresetFixedSupplyContext.Provider >
                                                    </TokenTimelockContext.Provider >
                                                </ERC20Context.Provider >
                                            </TokenBonfireContext.Provider >
                                        </MonkeBonfireContext.Provider >
                                    </NanerContext.Provider >
                                </MonkeContext.Provider >
                            </SimpleTokenTimelockContext.Provider >
                        </LogsContext.Provider >
                    </CurrentAddressContext.Provider>
                </SignerContext.Provider>
            </ProviderContext.Provider>
        </SymfoniContext.Provider>
    )

};
